version: "3"
services:
  myapp-dev:
    build:
      context: .
      target: development
    ports:
      - "5001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run build-watch-dev
  myapp-prod:
    build:
      context: .
      target: production
    ports:
      - "5002:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run build-watch-prod